# Header

menu:
  主页: /
  随笔: /categories/随笔/
  iOS: /categories/iOS/

# SubNav
subnav:
  github: "https://github.com/RobberJJ"
  #weibo: "#"
  #rss: "#"
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  jianshu: "http://www.jianshu.com/u/ddb6b7f61f04"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #mail: "mail:ro_bber@126.com"
  facebook: "https://www.facebook.com/profile.php?id=100015070143697"
  #google: "#"
  twitter: "https://twitter.com/Ro__bber"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root:

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /imgs/robberjj_zhifubao.png
# 微信二维码图片地址
weixin: /imgs/robberjj_weixin.png

# Miscellaneous
baidu_analytics: true
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /imgs/robberjj.png

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false #'63e09110fdfc4fa195d59eceb0fec863'

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: 'robberjj'

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#009fe1'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#11232b,#b8cfd7)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  #friends: '友链'
  aboutme: '关于我'

friends:
  简书（Ro_bber）: http://www.jianshu.com/u/ddb6b7f61f04
  Github（RobberJJ）: https://github.com/RobberJJ

aboutme: 即使，<br>没有人为你鼓掌，<br>也要优雅的谢幕，<br>感谢自己认真的付出！
